server:
  port: 7654

spring:
  application:
    name: hello-server
  kafka:
    bootstrap-servers: 172.17.0.2:46681
    consumer:
      group-id: hello-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
